### PR TITLE
update default login bg picture

### PR DESCRIPTION
**Pull request by demtzu**
before: https://images.unsplash.com/photo-1616795795564-fc2f3b2e9723?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2689&q=80

after: https://images.unsplash.com/photo-1518622513113-23963f3c16f1

### CODE REVIEW

**Comment by demtzu** [comment]
Just changed this one for now: https://images.unsplash.com/photo-1616795795564-fc2f3b2e9723?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2689&q=8 


Later
image

https://images.unsplash.com/photo-1518622513113-23963f3c16f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80

https://images.unsplash.com/photo-1622976480033-d7458ff18425?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2904&q=80

https://images.unsplash.com/photo-1479762937580-3b682a10a0d8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2832&q=80

https://images.unsplash.com/photo-1473123091594-424e04babfe1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80

https://images.unsplash.com/photo-1526289034009-0240ddb68ce3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2942&q=80

More tests: https://www.figma.com/file/gi3GVOX9D86cRGsBar2y32/Loader-%2F-Inbox-zero?node-id=1707%3A9196

**Comment by castroCrea** [comment]
You need to change the picture from tu current months there you change the picture from January 2022

**Comment by castroCrea** [comment]
So this file for august 2022/8/index.json

**Comment by demtzu** [comment]
Thanks 👍

**Comment by castroCrea** [comment]
I just add a readme 
https://github.com/lazy-daily-image/lazy-daily-image.github.io/blob/main/README.md

**Comment by demtzu** [comment]
@castroCrea I've edited folder 8 and 9 via github, I think i skipped the PR and committed directly to the main? 
image

Only the default picture works, right?
It's everyday this picture on my end:
image

**Comment by castroCrea** [comment]
No it works but this month and the previous there was only the default picture.

So it works as follow: It search for a picture at the day and if there is not it takes de default

**Comment by castroCrea** [comment]
So in September every day as a different picture you can check here https://lazy-daily-image.github.io/2022/9/preview.html
In august, you will have every day the default picture except on the 29/30/31 https://lazy-daily-image.github.io/2022/8/preview.html
image

image

**Comment by demtzu** [comment]
Great the preview feature! updated July and August, we can keep the same image for now as it's only on the login (not inbox0 anymore)

**Comment by demtzu** [comment]
@castroCrea I did some change on the main but it doesn't update, shouldn't it?

**Comment by castroCrea** [comment]
We download on the morning the daily and the default on the start of the months

**Comment by castroCrea** [comment]
Localy

**Pull request merged**
